#!/bin/bash
echo "Attempting to change GNOME settings..." >> /home/user/kickstart.log
echo "whoami= `whoami`" >> /home/user/kickstart.log

/usr/bin/gconftool-2 --type bool --set /desktop/gnome/remote_access/enabled false 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/gnome-screensaver/idle_activation_enabled false 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_computer_ac 0 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type int --set /apps/gnome-power-manager/timeout/sleep_display_ac 0 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/panel/toplevels/bottom_panel_screen0/auto_hide true 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/panel/toplevels/top_panel_screen0/auto_hide true 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/panel/toplevels/top_panel_screen0/x_centered true 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/panel/toplevels/top_panel_screen0/expand false 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/update-notifier/auto_launch false 2>> /home/user/kickstart.log
/usr/bin/gconftool-2 --type bool --set /apps/metacity/global_keybindings/run_command_terminal "<Shift><Alt>t" 2>> /home/user/kickstart.log
